# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20161116_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='id_estudio',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
        migrations.AddField(
            model_name='imagen',
            name='estudio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Estudio'),
        ),
    ]
