# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20161116_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
    ]
