# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugerenciadiagnostico',
            old_name='es_correto',
            new_name='es_correcto',
        ),
        migrations.AlterField(
            model_name='sugerenciadiagnostico',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
