# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20161113_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='id',
            field=models.CharField(max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_estudio',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_serie',
            field=models.CharField(max_length=55),
        ),
    ]
